site_name: pyggp
site_url: https://pyggp.github.io/
site_author: Lukas Grassauer
site_description: Python implementation of the General Game Playing (GGP) framework

repo_name: entze/pyggp
repo_url: https://github.com/entze/pyggp

copyright: Copyright &copy; 2023 Lukas Grassauer

theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            filters:
              - "!__repr__"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
