site_name: pyggp
site_url: https://pyggp.github.io/
site_author: Lukas Grassauer
site_description: Python implementation of the General Game Playing (GGP) framework

repo_name: entze/pyggp
repo_url: https://github.com/entze/pyggp

copyright: Copyright &copy; 2023 Lukas Grassauer

theme:
  name: material

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
          options:
            filters:
              - "!__repr__"


nav:
  - Overview: index.md
  - Contributing:
      - Overview: contributing/index.md
      - Testing: contributing/testing.md
  - Reference:
      - Overview: reference/index.md
      - actors: reference/actors.md
      - gdl: reference/gdl.md
