[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyggp"
version = "0.0.0"
description = "A Python implementation of the General Game Playing (GGP) framework."
authors = ["Lukas Grassauer <lukas@grassauer.eu>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "pyggp", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.11"
clingo = "~5.6.2"
clingox = "~1.2.0"
typer = "~0.7.0"
rich = "~13.3.1"
inflection = "~0.5.1"


[tool.poetry.group.ci]
optional = true

[tool.poetry.group.ci.dependencies]
tox = "~4.4.5"


[tool.poetry.group.citests]
optional = true

[tool.poetry.group.citests.dependencies]
tox-gh = "~1.0.0"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pre-commit = "~3.0.4"
commitizen = "~2.42.0"
black = "~23.1.0"
mypy = "~1.0.0"
pylint = "~2.16.2"
coverage = "~7.1.0"
tox = "~4.4.5"
darglint = "~1.8.1"
pydocstyle = "~6.3.0"
xdoctest = "~1.1.1"
pygments = "~2.14.0"
docformatter = "~1.5.1"
pytest = "~7.2.1"
tryceratops = "~1.1.0"


[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
pdoc = "~12.3.1"


[tool.black]
line-length = 120


[tool.coverage.run]
source = ['pyggp']


[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "raise AssertionError",
    "def __repr__",
    "if __name__ == .main.:"
]

[tool.commitizen]
name = "cz_conventional_commits"
bump_message = "chore(release): v$current_version -> v$new_version"
tag_format = "v$version"
update_changelog_on_bump = true
version = "0.0.0"
version_files = ["pyproject.toml:version"]


[tool.docformatter]
recursive = true
wrap-summaries = 120
wrap-descriptions = 120
blank = true


[tool.mypy]
implicit_reexport = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true


[tool.pylint]
max-line-length = 120
fail-under = 10


[tool.tryceratops]
exclude = [
    "tests",
    "docs",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    ".github"
]
