[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyggp"
version = "0.0.0"
description = "A Python implementation of the General Game Playing (GGP) framework."
authors = ["Lukas Grassauer <lukas@grassauer.eu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"

[tool.poetry.group.dev]

[tool.poetry.group.dev.dependencies]
pre-commit = "~3.0.4"
commitizen = "~2.42.0"
