name: "CI"

on:
  push:
    paths:
      - "src/"
      - "tests/"
      - "**.md"
      - "pyproject.toml"
      - "poetry.lock"
      - ".pre-commit-config.yaml"
      - ".pymarkdown-config.json"
      - "tox.ini"
      - ".github/workflows/ci.yaml"
  pull_request:

jobs:
  pre-commit:
    name: "✅ Pre-Commit (Python ${{ matrix.python-version }}, ${{ matrix.os }})"
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.11' ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pipx install poetry
      - uses: pre-commit/action@v3.0.0
  tox:
    name: "🐍 Tox QA (Python ${{ matrix.python-version }}, ${{ matrix.os }})"
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [ '3.11' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry install --with ci
      - uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-python${{ matrix.python-version }}-tox-${{ hashFiles('**/tox.ini') }}
      - run: poetry run tox run-parallel -m qa -v --notest
      - run: poetry run tox run-parallel -m qa --skip-pkg-install
