name: "CI"

on:
  push:
    paths:
      - "src/"
      - "tests/"
      - "**.md"
      - ".github/workflows/ci.yaml"
  pull_request:

jobs:
  pre-commit:
    name: "✅ Pre-Commit (Python ${{ python-version }}, {{ matrix.os }})"
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.11' ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v3.0.0
  tox:
    name: "🐍 Tox (Python ${{ matrix.python-version }}, ${{ matrix.os }})"
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [ '3.11' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: pipx install poetry
      - run: poetry install
      - run: poetry run tox run-parallel -m qa -vv --notest
      - run: poetry run tox run-parallel -m qa --skip-pkg-install
