name: "Test"
on:
  push:
    branches:
      - main
    paths:
      - "src/"
      - "tests/"
      - ".github/workflows/test.yaml"
  pull_request:

jobs:
  tox:
    name: "🐍 Tox (Python ${{ matrix.python-version }}, ${{ matrix.os }})"
    timeout-minutes: 10
    strategy:
      matrix:
        python-version:
          - '3.11'
          - 'pypy3.11'
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
          - os: macos-latest
            python-version: 'pypy3.11'
          - os: windows-latest
            python-version: 'pypy3.11'
          - os: ubuntu-latest
            python-version: 'pypy3.11'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install tox tox-gh
      - run: tox run --skip-env "(lint|type|format|docs)" -vv --notest
      - run: tox run --skip-env "(lint|type|format|docs)" --skip-pkg-install
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.11' }} && ${{ matrix.os == 'ubuntu-latest' }}
