name: "Tests"

on:
  push:
    paths:
      - "src/"
      - "tests/"
      - "tox.ini"
      - ".github/workflows/tests.yaml"
  pull_request:

jobs:
  tox:
    name: "🐍 Tox Tests (Python ${{ matrix.python-version }}, ${{ matrix.os }})"
    timeout-minutes: 10
    strategy:
      matrix:
        python-version:
          - '3.11'
          - 'pypy3.11'
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
          - os: macos-latest
            python-version: 'pypy3.11'
          - os: windows-latest
            python-version: 'pypy3.11'
          - os: ubuntu-latest
            python-version: 'pypy3.11'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry install --with ci,citests
      - uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-python${{ matrix.python-version }}-tox-${{ hashFiles('**/tox.ini') }}
      - run: poetry run tox run -m tests -v --notest
      - run: poetry run tox run -m tests --skip-pkg-install
  coverage:
    name: "📊 Coverage (Python ${{ matrix.python-version }}, ${{ matrix.os }})"
    needs: tox
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [ '3.11' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry install --with ci
      - uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-python${{ matrix.python-version }}-tox-${{ hashFiles('**/tox.ini') }}
      - run: poetry run tox run -e coverage -v --notest
      - run: poetry run tox run -e coverage --skip-pkg-install
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
