name: "Test"
on:
  push:
    branches:
      - main
    paths:
      - "src/"
      - "tests/"
      - ".github/workflows/test.yaml"
  pull_request:

jobs:
  tox:
    name: "🐍 Tox (Python ${{ matrix.python-version }}, ${{ matrix.os }})"
    timeout-minutes: 10
    strategy:
      matrix:
        python-version:
          - '3.11'
          - 'pypy-3.11'
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install tox tox-gh
      - run: tox run -vv --notest
      - run: tox run --skip-pkg-install
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.11' }}
